In [2]:
import pandas as pd

In [5]:
video_df = pd.read_pickle("../data/Video2Features.pkl")

In [6]:
audio_df = pd.read_pickle("../data/Audio2Features.pkl")

In [9]:
audio_df.head()

,FILE,SEG,CLASS_1,0,1,2,3,4,5,6,...,58,59,60,61,62,63,64,65,66,67
0,speaker1,0,boring,0.183553,0.012248,2.900870,0.268965,0.216874,1.425944,0.029339,...,0.028343,0.010286,0.005941,0.074841,0.006697,0.002692,0.010131,0.019190,0.008569,0.018438
1,speaker1,1,neutral,0.240748,0.016341,2.839751,0.318596,0.211565,1.553694,0.022397,...,0.051219,0.031334,0.012365,0.032233,0.009938,0.011444,0.008333,0.013767,0.013939,0.015767
2,speaker2,0,neutral,0.209113,0.008564,2.543946,0.323341,0.219840,1.728043,0.019598,...,0.015357,0.024071,0.026557,0.029198,0.008224,0.011878,0.010195,0.013334,0.006455,0.012702
3,speaker2,1,exciting,0.198956,0.006934,2.729110,0.325868,0.221844,1.599395,0.021568,...,0.011182,0.004687,0.009305,0.107418,0.002656,0.024336,0.016720,0.018498,0.013210,0.027409

In [10]:
video_df.head()

,FILE,SEG,CLASS_1,0,1,2,3,4,5,6,...,25078,25079,25080,25081,25082,25083,25084,25085,25086,25087
0,speaker1,0,boring,0.0,3.450885,1.179175,0.0,0.0,0.0,2.813062,...,20.059443,0.0,1.031235,0.0,0.000000,0.0,1.870711,6.2898,19.627050,0.403226
1,speaker1,1,neutral,0.0,15.276594,1.038574,0.0,0.0,0.0,2.161670,...,26.400854,0.0,0.956505,0.0,4.346704,0.0,0.454285,0.0000,28.739689,0.000000
2,speaker2,0,neutral,0.0,3.450885,1.179175,0.0,0.0,0.0,2.813062,...,20.059443,0.0,1.031235,0.0,0.000000,0.0,1.870711,6.2898,19.627050,0.403226
3,speaker2,1,exciting,0.0,15.276594,1.038574,0.0,0.0,0.0,2.161670,...,26.400854,0.0,0.956505,0.0,4.346704,0.0,0.454285,0.0000,28.739689,0.000000